In [9]:
import numpy as np

In [1]:
import pandas as pd

In [2]:
#series
data=[1,2,3,4,5]
print(pd.Series(data))

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
dict={"a":1,"b":2,"c":3}
print(pd.Series(dict))

a    1
b    2
c    3
dtype: int64

In [4]:
value=[1,2,3,4,5]
index=["a","b","c","d","e"]
print(pd.Series(value, index=index))

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [10]:
## Dataframe
## create a Dataframe from a dictionary oof list

data={
    'Name':['Krish','John','Jack'],
    'Age':[25,np.nan,45],
    'City':['Bangalore','New York','Florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name   Age       City
0  Krish  25.0  Bangalore
1   John   NaN   New York
2   Jack  45.0    Florida
<class 'pandas.DataFrame'>

In [13]:
## Remove a column
df.drop('City',axis=1)

    Name   Age
0  Krish  25.0
1   John   NaN
2   Jack  45.0

In [14]:
df.fillna(0)

    Name   Age       City
0  Krish  25.0  Bangalore
1   John   0.0   New York
2   Jack  45.0    Florida